# core/pdf_report.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
import tempfile
import os
from .interpretations import get_interpretation
from PIL import Image

def create_pdf_report(pdf_path: str, results: dict, grid_image=None):
    """
    Create a PDF report using reportlab.
    - pdf_path: output filename
    - results: dict with keys name, dob (datetime.date), gender, mulank, bhagyank, name_number, angel
    - grid_image: PIL.Image instance (optional) to include (Lo Shu grid)
    """
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    margin = 50
    y = height - margin

    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin, y, "Numerology Report")
    y -= 28

    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Full Name: {results.get('name','')}")
    y -= 16
    dob = results.get('dob')
    c.drawString(margin, y, f"Date of Birth: {dob.isoformat() if dob else ''}")
    y -= 16
    c.drawString(margin, y, f"Gender: {results.get('gender','')}")
    y -= 26

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y, "Computed Numbers")
    y -= 18
    c.setFont("Helvetica", 12)
    items = [
        ("Mulank (Birth Number)", results.get('mulank')),
        ("Bhagyank (Destiny Number)", results.get('bhagyank')),
        ("Name Number (Chaldean)", results.get('name_number')),
        ("Angel Number", results.get('angel'))
    ]
    for label, val in items:
        c.drawString(margin, y, f"{label}: {val}")
        y -= 16

    y -= 8
    # Interpretations
    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y, "Short Interpretations")
    y -= 18
    c.setFont("Helvetica", 10)
    for label, val in items:
        if val is None:
            continue
        interp = get_interpretation(int(val)) if str(val).isdigit() else ""
        c.drawString(margin, y, f"{label} ({val}): {interp}")
        y -= 14
        if y < margin + 120:
            c.showPage()
            y = height - margin

    # Place Lo Shu grid image on the right side or new page if not enough space
    if grid_image:
        # Save to temp file
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
        tmpname = tmp.name
        tmp.close()
        # ensure image is RGB
        if grid_image.mode in ("RGBA", "P"):
            grid_image = grid_image.convert("RGB")
        grid_image.save(tmpname, format="PNG")
        # attempt to draw on the page
        try:
            # if room on current page
            if y - 300 < margin:
                c.showPage()
                y = height - margin
            img_width = 300
            img_height = 300
            c.drawImage(ImageReader(tmpname), width - margin - img_width, height - margin - img_height, img_width, img_height)
        finally:
            os.unlink(tmpname)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawString(margin, margin - 10, "Generated by Numerology Analyzer")
    c.save()
